language: python
sudo: false
matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=dist
    - python: 3.8
      env: TOXENV=docs
    - python: 3.8
      env: TOXENV=manifest
install:
  - pip install tox coverage codecov
script:
  - tox -e $TOXENV
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TOXENV = "py38" &&
    coverage xml -i
  - test $TRAVIS_BRANCH = "master" &&
    test $TOXENV = "py38" &&
    codecov
