name: Check Release
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  check_release:
    runs-on: ubuntu-latest
    # check-release runs a full dry-run release cycle, which creates (and cleans up)
    # a draft GitHub release.
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@95d85449e4f3f352e261221f6529f8ed307f5728 # v1
      - name: Install Dependencies
        shell: bash
        run: |
          pip install -e .
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@634ac751f8a58d3d4a19b63f58aad138e6355cc8 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
